### ISSUE TITLE
Can we draw shapes (Circle,Rect,Arrow etc ?)

### ISSUE THREAD

**Issue by Suyash171** [burhanrashid52/PhotoEditor#274] opened 2020-09-07 11:56 UTC

**Comment by ankitivo** [comment] 2020-09-12 12:17
No, it's not possible at the moment. I am also looking for that feature too.

**Comment by ankitbatra11** [comment] 2020-09-12 12:19
No, it's not possible at the moment. I am looking out for that feature support.

**Comment by burhanrashid52** [comment] 2020-09-15 08:49
Duplicate of #72

**Closed by burhanrashid52** 2020-09-15 08:49 UTC
Labels: duplicate

**Comment by abuzer** [comment] 2020-12-30 17:36
@ankitbatra11 / @burhanrashid52 Is it still not supported? Any chances to be add this feature in near future if not added.
