### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: Cannot set 'scaleX' to Float.NaN

### ISSUE THREAD

**Issue by bojjaradhakrishna** [burhanrashid52/PhotoEditor#265] opened 2020-08-02 13:37 UTC
Dear Author,

Thanks a lot for the library.
We faced a crash while resizing an added image onto the actual photo. or it could be during drawing pen(not very sure about this).
We got it only once, so could not exactly find steps to reproduce.
Could you please consider fixing this.

Fatal Exception: java.lang.IllegalArgumentException: Cannot set 'scaleX' to Float.NaN
       at android.view.View.sanitizeFloatPropertyValue(View.java:15585)
       at android.view.View.sanitizeFloatPropertyValue(View.java:15559)
       at android.view.View.setScaleX(View.java:14948)
       at ja.burhanrashid52.photoeditor.e.n(MultiTouchListener.java:5)
       at ja.burhanrashid52.photoeditor.e.h(MultiTouchListener.java:1)
       at ja.burhanrashid52.photoeditor.e$e.c(MultiTouchListener.java:10)
       at ja.burhanrashid52.photoeditor.m.i(ScaleGestureDetector.java:67)
       at ja.burhanrashid52.photoeditor.e.onTouch(MultiTouchListener.java:1)
       at android.view.View.dispatchTouchEvent(View.java:12624)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3035)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2714)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3063)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:565)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1929)
       at android.app.Dialog.dispatchTouchEvent(Dialog.java:1061)
       at android.inputmethodservice.SoftInputWindow.dispatchTouchEvent(SoftInputWindow.java:93)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:514)
       at android.view.View.dispatchPointerEvent(View.java:12873)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5771)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5535)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4983)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5036)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5002)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5157)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5010)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5214)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4983)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5036)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5002)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5010)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4983)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7803)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7768)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7726)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8007)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:202)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:191)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7917)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8061)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
       at android.view.Choreographer.doCallbacks(Choreographer.java:893)
       at android.view.Choreographer.doFrame(Choreographer.java:806)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

Regards,
Radhakrishna.

**Comment by burhanrashid52** [comment] 2020-09-15 09:53
Since the occurrence of this issue is low and it's hard to reproduce. We are closing this issue for now. If anyone faces this similar issue again, please reopen the ticket.

**Closed by burhanrashid52** 2020-09-15 09:53 UTC
