### ISSUE TITLE
The character disappears when the image is saved.

### ISSUE THREAD

**Issue by hololee** [burhanrashid52/PhotoEditor#5] opened 2018-02-14 05:29 UTC
After writing a character in the view, the character disappears when i save the image.

**Comment by burhanrashid52** [comment] 2018-02-14 05:47
You mean adding special character in text ? Can you elaborate ?

**Comment by hololee** [comment] 2018-02-14 05:54
i add the text in korean and save the image. after saving image, the text in the view disappeare

**Comment by burhanrashid52** [comment] 2018-02-14 07:28
I am not able to reproduce the issue.I tried by changing language input to Korean and its works fine

**Comment by hololee** [comment] 2018-02-14 07:56
Saved image is fine but in photoeditorview the character was disappearing.

**Comment by burhanrashid52** [comment] 2018-02-14 08:00
You meant you are able to save image with Korean text but not able to see in `PhotoEditorView` , right ?

**Comment by hololee** [comment] 2018-02-14 08:01
yes :( sorry. i am not good at english..

**Comment by hololee** [comment] 2018-02-14 11:10
ah  after i save the image(i made customButton, when i clicked this button), the text on the photoeditview is disappeared.

**Comment by burhanrashid52** [comment] 2018-02-16 12:37
Can you provide  stack-trace/error or a screenshot/video which will be helpful

**Comment by burhanrashid52** [comment] 2018-03-07 05:58
Not enough information to reproduce the issue....closing this issue for now

**Closed by burhanrashid52** 2018-03-07 05:58 UTC
