### ISSUE TITLE
ArrayIndexOutOfBoundsException at ja.burhanrashid52.photoeditor.BitmapUtil.removeTransparency (BitmapUtil.java:46)

### ISSUE THREAD

**Issue by ankitbatra11** [burhanrashid52/PhotoEditor#263] opened 2020-07-24 20:17 UTC
I have crash reports of ArrayIndexOutOfBoundsException through Crashlytics in my app:

`java.lang.RuntimeException: 
  at android.os.AsyncTask$3.done (AsyncTask.java:353)
  at java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:383)
  at java.util.concurrent.FutureTask.setException (FutureTask.java:252)
  at java.util.concurrent.FutureTask.run (FutureTask.java:271)
  at android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:245)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
  at java.lang.Thread.run (Thread.java:764)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 
  at ja.burhanrashid52.photoeditor.BitmapUtil.removeTransparency (BitmapUtil.java:46)
  at ja.burhanrashid52.photoeditor.PhotoEditor$6$1.doInBackground (PhotoEditor.java:743)
  at ja.burhanrashid52.photoeditor.PhotoEditor$6$1.doInBackground (PhotoEditor.java:730)
  at android.os.AsyncTask$2.call (AsyncTask.java:333)
  at java.util.concurrent.FutureTask.run (FutureTask.java:266)
  at android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:245)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
  at java.lang.Thread.run (Thread.java:764)`

Unfortunately, I cannot provide any more information at the moment other than this.

I am using `implementation 'ja.burhanrashid52:photoeditor:1.0.0'`

**Comment by AdhseOne** [comment] 2020-07-29 06:29
Mmm ... it seems that you are sending a Bitmap, which is not null, but has not finished generating and possibly its measurements are 0.

**Comment by AdhseOne** [comment] 2020-07-30 00:30
> I have crash reports of ArrayIndexOutOfBoundsException through Crashlytics in my app:
> 
> `java.lang.RuntimeException: at android.os.AsyncTask$3.done (AsyncTask.java:353) at java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:383) at java.util.concurrent.FutureTask.setException (FutureTask.java:252) at java.util.concurrent.FutureTask.run (FutureTask.java:271) at android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:245) at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162) at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636) at java.lang.Thread.run (Thread.java:764) Caused by: java.lang.ArrayIndexOutOfBoundsException: at ja.burhanrashid52.photoeditor.BitmapUtil.removeTransparency (BitmapUtil.java:46) at ja.burhanrashid52.photoeditor.PhotoEditor$6$1.doInBackground (PhotoEditor.java:743) at ja.burhanrashid52.photoeditor.PhotoEditor$6$1.doInBackground (PhotoEditor.java:730) at android.os.AsyncTask$2.call (AsyncTask.java:333) at java.util.concurrent.FutureTask.run (FutureTask.java:266) at android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:245) at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162) at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636) at java.lang.Thread.run (Thread.java:764)`
> 
> Unfortunately, I cannot provide any more information at the moment other than this.
> 
> I am using `implementation 'ja.burhanrashid52:photoeditor:1.0.0'`

Mmm ... it seems that you are sending a Bitmap, which is not null, but has not finished generating and possibly its measurements are 0.

**Comment by Parag2385** [comment] 2020-07-31 07:14
@ankitbatra11 Same here, I'm also observing this exception in Crashlytics, Did you find a solution to it?

**Comment by ankitbatra11** [comment] 2020-08-01 07:09
I believe that this could be triggered if I let the user click the `Save` edited image button multiple times without letting the user wait (via a progress bar) until the edited image from the previous `Save` button click is saved. '

Hence, I am currently adding a progress bar on `Save` click so as to not let the user go mad with the `Save` button if saving the edited image takes time. It may or may not fix the issue but is anyway a good change for my app.

**Comment by Parag2385** [comment] 2020-08-01 08:48
@ankitbatra11 Ohh yeah, makes sense, depending on the size of the processed image, it could take different time on different devices, might take more time on lower-end devices. Thanks, I'll also try this.

**Comment by ankitbatra11** [comment] 2020-09-04 22:00
Happened to see another occurrence in the production instance of my app
```
Caused by java.lang.ArrayIndexOutOfBoundsException: length=1501200; index=1501200
       at ja.burhanrashid52.photoeditor.BitmapUtil.removeTransparency(BitmapUtil.java:46)
       at ja.burhanrashid52.photoeditor.PhotoEditor$6$1.doInBackground(PhotoEditor.java:743)
       at ja.burhanrashid52.photoeditor.PhotoEditor$6$1.doInBackground(PhotoEditor.java:730)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```
Looks like a bug in the code snippet below (taken from `BitmapUtil.removeTransparency`)
```
loop:
        for (int y = 0; y < source.getHeight(); y++) {
            for (int x = firstX; x < source.getHeight(); x++) {
                if (pixels[x + (y * source.getWidth())] != Color.TRANSPARENT) {
                    firstY = y;
                    break loop;
                }
            }
        }
```
` for (int x = firstX; x < source.getHeight(); x++) {` should be  `for (int x = firstX; x < source.getWidth(); x++) {`

**Comment by burhanrashid52** [comment] 2020-09-15 09:19
@ankitbatra11 Thanks for the PR. I will have a look at it. Are you able to reproduce the issue in your device, because it will help us to verify the fix.

**Comment by burhanrashid52** [comment] 2020-09-15 09:32
Merged in release.1.1.0

**Comment by Parag2385** [comment] 2020-09-15 10:51
Have you released the version 1.1.0? as it's not showing up on bintray.
https://bintray.com/burhanrashid52/maven/photoeditor

**Comment by burhanrashid52** [comment] 2020-09-15 11:01
Not yet. Need to review other PR as well. Once it get merged I will release it. I should've not closed this ticket.

**Comment by Parag2385** [comment] 2020-09-15 11:06
Is there any chance that you'll be releasing it by Friday? As I'm releasing an app update on Friday and I see a lot of users having this error/crash on their devices. If you could release it by Friday that would be really great. Thanks.

**Comment by ankitbatra11** [comment] 2020-09-15 21:52
> @ankitbatra11 Thanks for the PR. I will have a look at it. Are you able to reproduce the issue in your device, because it will help us to verify the fix?

Sorry, can't reproduce it. Already using the fix in the production instance of my app. Will try to update here if I see this issue again.

**Closed** 2020-11-01 02:58 UTC
Labels: bug, release.1.1.0
