### ISSUE TITLE
get/set drawing?

### ISSUE THREAD

**Issue by SmailHammour** [burhanrashid52/PhotoEditor#571] opened 2024-10-17 15:12 UTC
Hello there,

I'm using this library mainly as a drawing tool. So the idea behind it that I'm setting a clear bitmap (using setImageBitmap) with a set width and height and I'm drawing on that. 

* I was wondering how I can set the previous bitmap (set in saveAsBitmap) so I can continue the drawing? I tried to set the saved drawing with `setImageBitmap` but it's just setting it as an image and the new drawing is going on top of that.
* Is there a way to get the full drawing when using `saveAsBitmap` instead of just the drawed area?

Thanks in advance.

**Comment by SmailHammour** [comment] 2024-10-24 06:10
@burhanrashid52 any idea?

**Comment by burhanrashid52** [comment] 2024-10-24 11:32
Sorry, Maybe I don't understand your use case....If you just want to use as a drawing tool, can't you use a white image and draw on top of it? Like a whiteboard?

**Comment by SmailHammour** [comment] 2024-10-24 12:44
@burhanrashid52 yes, that's what I'm already doing, but I was wondering if I could save the drawing and continue where I previously left?

**Comment by SmailHammour** [comment] 2024-10-28 20:14
@burhanrashid52 is that clear to you?

**Comment by burhanrashid52** [comment] 2024-10-29 10:48
> @burhanrashid52 is that clear to you?

No, I still don't understand. Do you want to save the drawing element state and restore it for a different image? If yes, then I think it is a duplicate of #119 and #26.

**Comment by SmailHammour** [comment] 2024-10-30 07:31
Hmm, I'm not sure how to explain it more clearly than I already did.

Do you know MS Paint where you can draw in freeform? So what I would like to do is to draw on a blank canvas. When I finish drawing I would like to store the drawing I made drawing in freeform. After a while when I decide to continue said drawing, I would like to load it back so I can continue using the drawing that I stored when I finished.

I hope this is clear because I don't know what else I could add.

**Comment by burhanrashid52** [comment] 2024-10-31 06:25
> I would like to load it back so I can continue using the drawing that I stored when I finished.

@SmailHammour Thanks exactly #119 and #26 issue is for. The ability to load drawing anytime. For now its not possible because it require some persistence layer to save all the info and reload it again and I don't have bandwidth for now.

**Comment by burhanrashid52** [comment] 2024-10-31 06:26
Duplicate of #119 and #26

**Closed by burhanrashid52** 2024-10-31 06:26 UTC
Labels: duplicate
