### ISSUE TITLE
Quality of saved image is lower. How can I work with high quality images

### ISSUE THREAD

**Issue by BerdiyorovAbrorjon** [burhanrashid52/PhotoEditor#337] opened 2021-04-09 15:11 UTC
Image quality is average when saving as a bitmap. I got the image in bitmap format and save it in .bmp format. But the image quality is lower. What do I need to do to get a high quality picture. Please help me

**Comment by burhanrashid52** [comment] 2021-04-10 10:33
Duplicate of #10

**Closed by burhanrashid52** 2021-04-10 10:33 UTC
