### ISSUE TITLE
Image not saving

### ISSUE THREAD

**Issue by Anurag--Singh** [burhanrashid52/PhotoEditor#40] opened 2018-05-31 08:26 UTC
Great work! Very useful.

I have cloned the repository and ran the sample app. Image is not saving even on pressing the save button.

If I capture the image, choose the image from the gallery or use the default image for the `PhotoEditorView` , save option doesn't works. 

`mProgressDialog` is not removing. I checked the image and found the file is created with name **1527754743495.png** but no output is written in it.

I tried rebooting the phone but not working.

Here are the logs:

**Device:** Nexus 5x
**OS version:** 8.1.0

```
05-31 13:49:03.497 8982-8982/com.burhanrashid52.imageeditor D/PhotoEditor: Image Path: /storage/emulated/0/1527754743495.png
05-31 13:49:03.618 8982-8989/com.burhanrashid52.imageeditor I/zygote64: Do partial code cache collection, code=47KB, data=58KB
    After code cache collection, code=47KB, data=58KB
    Increasing code cache capacity to 256KB
    Compiler allocated 4MB to compile void android.view.View.<init>(android.content.Context, android.util.AttributeSet, int, int)
05-31 13:49:03.818 8982-8989/com.burhanrashid52.imageeditor I/zygote64: Compiler allocated 7MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
05-31 13:49:03.838 8982-8989/com.burhanrashid52.imageeditor I/zygote64: Do full code cache collection, code=124KB, data=79KB
05-31 13:49:03.839 8982-8989/com.burhanrashid52.imageeditor I/zygote64: After code cache collection, code=78KB, data=39KB
```

**Comment by riteshram** [comment] 2018-06-01 10:32
Same issue with Samsung Galaxy Tab S3, OS Ver: 8.0.0

**Comment by burhanrashid52** [comment] 2018-06-01 10:35
Thanks for the update I am working on it. Please share the stacktrace

**Comment by burhanrashid52** [comment] 2018-06-01 10:37
Are you able to save the image with version 0.1.1? @Anurag--Singh @riteshram

**Comment by riteshram** [comment] 2018-06-01 10:54
@burhanrashid52 Yup works fine with version 0.1.1.

**Comment by burhanrashid52** [comment] 2018-06-01 10:59
Is it the device or OS specific issue ? have you tried with other devices and OS versions?

**Comment by riteshram** [comment] 2018-06-01 11:09
No i don't think it's OS specific, tested it with Redmi Note 3 OS ver 6.0.1 as well.

**Comment by sgdesmet** [comment] 2018-06-01 11:12
Same issue on a Samsung A3. Seems like `onDrawFrame` in `ImageFilterView` is never called after doing `requestRender` in `saveBitmap`. Haven't had the time yet to check out why.

**Comment by Jiks19** [comment] 2018-06-01 13:04
Same issue with Redmi note 3

**Comment by Anurag--Singh** [comment] 2018-06-02 05:55
@burhanrashid52 I will let you know the result against version 0.1.1.

**Comment by burhanrashid52** [comment] 2018-06-02 09:30
Are you able to apply the effect on source image using `setFilterEffect` method ? @Anurag--Singh @riteshram @Jiks19 @sgdesmet

**Comment by Jiks19** [comment] 2018-06-02 10:15
@burhanrashid52 

I have without apply filter effect save my image.

**Comment by burhanrashid52** [comment] 2018-06-02 10:19
So you are able to save image without any effect right ?
My question is are you able to apply the effect using `setFilterEffect` method and able to see the effect preview on source image ?

**Comment by roudabeh** [comment] 2018-06-02 10:57
Hi
when I use Photo Editor version 0.2.0 , I couldn't save Image no way. with or without filter or anything else.
So I go back to version 0.1.0 and everything work well.

**Comment by riteshram** [comment] 2018-06-02 11:38
@burhanrashid52 Are you able to apply the effect on source image using setFilterEffect method ?
Yes filter effects can be applied, but cannot save the image in both cases.

**Comment by burhanrashid52** [comment] 2018-06-02 12:10
I have test with various devices available with me i.e  lenovo k4 , oneplus 3, samsung tab 2, samsung s6 its working fine in all the devices
If it would be very helpful if you can debug in your device weather `onDrawFrame` in `ImageFilterView` is called after doing `requestRender` in `saveBitmap` and able to generate bitmap or it throws any error
Thanks in advance

**Comment by Anurag--Singh** [comment] 2018-06-03 05:42
Sure, I will test it on all the nexus,  a few lg devices on **Monday**. Will share the result as instructed above.
Thank-you for the time.

**Comment by roudabeh** [comment] 2018-06-03 09:02
My problem solved and I can save file in version 0.2.0 with filters. The problem was I didn't add folder Filters (filters jpg are there) in assets folder of my project. Thanks a lot.

**Comment by roudabeh** [comment] 2018-06-03 10:03
The problem is when you have no filter. If I set filter on photo it saved correctly but without filter and mProgressDialog is not removing.

**Comment by Shajeel-Afzal** [comment] 2018-06-03 10:08
I am also facing the same error.

**Comment by burhanrashid52** [comment] 2018-06-03 12:31
Thanks, @roudabeh for analyzing the bug
I have resolved this issue and pushed the changes to the commit `20d2a15d5cbce008d78032b471dc4d8c08c1fec9` on master branch
So take the lastest pull from the master, check the issue and please do let me know

**Comment by burhanrashid52** [comment] 2018-06-03 16:41
This issue has been fixed in version 0.2.1

**Closed by burhanrashid52** 2018-06-03 16:41 UTC
Labels: bug

**Comment by roudabeh** [comment] 2018-06-07 05:47
Thanks a lot for your help, I Updated to version 0.2.1 and everything works well.

**Comment by Abhilash1307** [comment] 2018-09-25 12:48
I have used you code but it is not showing filtering or effect related functionality it is just showing Picture .that i have set from drawable only.

**Comment by burhanrashid52** [comment] 2018-09-25 17:02
Can you share more details?

**Comment by Abhilash1307** [comment] 2018-09-26 04:54
ok i think their may be issue with photoEditor i have used your Photoeditor class. i have used your code from top to bottom.it is not giving any kind of error but when i am using the app it is not showing toolbar for photo editing related functionality

**Comment by Abhilash1307** [comment] 2018-09-26 05:45
Please Tell me which photo editor sdk i have to use

**Comment by tsandun** [comment] 2021-12-08 12:22
Same issue in huawei.First time saved.after that not saving,
using => api 'ja.burhanrashid52:photoeditor:1.1.0'
Used others versions also.same issue.
Got an error from Async.java => "An error occurred while executing doInBackground()".
