### ISSUE TITLE
Sometimes happens "java.lang.IndexOutOfBoundsException"

### ISSUE THREAD

**Issue by daohieu91** [burhanrashid52/PhotoEditor#162] opened 2019-06-10 23:51 UTC
It faced this issue sometimes, but do not know how to reproduce. Please help! I guessed it happens in saveImage() function.

java.lang.IndexOutOfBoundsException: 
  at java.util.ArrayList.get (ArrayList.java:437)
  at android.view.ViewGroup.getAndVerifyPreorderedView (ViewGroup.java:3816)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4330)
  at android.view.View.draw (View.java:21734)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4558)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4333)
  at android.view.View.buildDrawingCacheImpl (View.java:21131)
  at android.view.View.buildDrawingCache (View.java:20997)
  at android.view.View.getDrawingCache (View.java:20833)
  at android.view.View.draw (View.java:21588)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4558)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4333)
  at android.view.View.draw (View.java:21734)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4558)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4333)
  at android.view.View.draw (View.java:21871)
  at android.view.View.draw (View.java:21736)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4558)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4333)
  at android.view.View.draw (View.java:21734)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4558)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4333)
  at android.view.View.draw (View.java:21734)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4558)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4333)
  at android.view.View.draw (View.java:21734)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4558)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4333)
  at android.view.View.draw (View.java:21734)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4558)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4333)
  at android.view.View.draw (View.java:21871)
  at com.android.internal.policy.DecorView.draw (DecorView.java:1139)
  at android.view.ViewRootImpl.drawSoftware (ViewRootImpl.java:4105)

**Comment by Joeydelarago** [comment] 2019-08-01 12:45
I am having what seems to be the same issue when I try to save an image that has a sticker on it that is too large. 

2019-08-01 11:57:08.156 11355-11355/net.overc.android.mobile E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.overc.android.mobile, PID: 11355
    java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at android.view.ViewGroup.getAndVerifyPreorderedView(ViewGroup.java:3809)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4323)
        at android.view.View.draw(View.java:21726)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
        at android.view.View.draw(View.java:21863)
        at android.view.View.buildDrawingCacheImpl(View.java:21129)
        at android.view.View.buildDrawingCache(View.java:20989)
        at android.view.View.draw(View.java:21578)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1873)
        at android.view.View.draw(View.java:21863)
        at android.view.View.updateDisplayListIfDirty(View.java:20733)
        at android.view.View.draw(View.java:21586)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
        at android.view.View.draw(View.java:21863)
        at androidx.core.widget.NestedScrollView.draw(NestedScrollView.java:1934)
        at android.view.View.updateDisplayListIfDirty(View.java:20733)
        at android.view.View.draw(View.java:21586)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1256)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
        at android.view.View.updateDisplayListIfDirty(View.java:20719)
        at android.view.View.draw(View.java:21586)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1873)
        at android.view.View.updateDisplayListIfDirty(View.java:20719)
        at android.view.View.draw(View.java:21586)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
        at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
        at android.view.View.updateDisplayListIfDirty(View.java:20719)
        at android.view.View.draw(View.java:21586)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
        at android.view.View.updateDisplayListIfDirty(View.java:20719)
        at android.view.View.draw(View.java:21586)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
        at android.view.View.updateDisplayListIfDirty(View.java:20719)
        at android.view.View.draw(View.java:21586)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
        at android.view.View.updateDisplayListIfDirty(View.java:20719)
        at android.view.View.draw(View.java:21586)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
        at android.view.View.updateDisplayListIfDirty(View.java:20719)
        at android.view.View.draw(View.java:21586)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
        at android.view.View.draw(View.java:21863)
        at com.android.internal.policy.DecorView.draw(DecorView.java:1083)
        at android.view.View.updateDisplayListIfDirty(View.java:20733)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:725)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:731)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:840)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3932)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3706)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3014)
2019-08-01 11:57:08.157 11355-11355/net.overc.android.mobile E/AndroidRuntime:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1873)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8478)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6990)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

**Comment by martarodriguezm** [comment] 2019-10-10 07:45
Hi,

Same problem here, it happens que the app is in the background or the phone screen is off.
The problem seems to be here: ja.burhanrashid52.photoeditor.PhotoEditor$6$1.doInBackground (PhotoEditor.java:743)

Caused by java.lang.IndexOutOfBoundsException 
java.util.ArrayList.get (ArrayList.java:437)
android.view.ViewGroup.getAndVerifyPreorderedView (ViewGroup.java:3659)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:4147)
android.view.View.draw (View.java:21308)
android.view.ViewGroup.drawChild (ViewGroup.java:4388)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:4149)
android.view.View.buildDrawingCacheImpl (View.java:20704)
android.view.View.buildDrawingCache (View.java:20570)
android.view.View.getDrawingCache (View.java:20406)
android.view.View.getDrawingCache (View.java:20357)
ja.burhanrashid52.photoeditor.PhotoEditor$6$1.doInBackground (PhotoEditor.java:743)
ja.burhanrashid52.photoeditor.PhotoEditor$6$1.doInBackground (PhotoEditor.java:730)
android.os.AsyncTask$3.call (AsyncTask.java:378)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:289)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:919)

Thanks,

**Comment by hamza-ahmed** [comment] 2020-02-06 09:39
> I am having what seems to be the same issue when I try to save an image that has a sticker on it that is too large.
> 
> 2019-08-01 11:57:08.156 11355-11355/net.overc.android.mobile E/AndroidRuntime: FATAL EXCEPTION: main
> Process: net.overc.android.mobile, PID: 11355
> java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
> at java.util.ArrayList.get(ArrayList.java:437)
> at android.view.ViewGroup.getAndVerifyPreorderedView(ViewGroup.java:3809)
> at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4323)
> at android.view.View.draw(View.java:21726)
> at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
> at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
> at android.view.View.draw(View.java:21863)
> at android.view.View.buildDrawingCacheImpl(View.java:21129)
> at android.view.View.buildDrawingCache(View.java:20989)
> at android.view.View.draw(View.java:21578)
> at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
> at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
> at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1873)
> at android.view.View.draw(View.java:21863)
> at android.view.View.updateDisplayListIfDirty(View.java:20733)
> at android.view.View.draw(View.java:21586)
> at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
> at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
> at android.view.View.draw(View.java:21863)
> at androidx.core.widget.NestedScrollView.draw(NestedScrollView.java:1934)
> at android.view.View.updateDisplayListIfDirty(View.java:20733)
> at android.view.View.draw(View.java:21586)
> at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
> at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1256)
> at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
> at android.view.View.updateDisplayListIfDirty(View.java:20719)
> at android.view.View.draw(View.java:21586)
> at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
> at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
> at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1873)
> at android.view.View.updateDisplayListIfDirty(View.java:20719)
> at android.view.View.draw(View.java:21586)
> at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
> at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
> at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
> at android.view.View.updateDisplayListIfDirty(View.java:20719)
> at android.view.View.draw(View.java:21586)
> at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
> at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
> at android.view.View.updateDisplayListIfDirty(View.java:20719)
> at android.view.View.draw(View.java:21586)
> at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
> at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
> at android.view.View.updateDisplayListIfDirty(View.java:20719)
> at android.view.View.draw(View.java:21586)
> at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
> at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
> at android.view.View.updateDisplayListIfDirty(View.java:20719)
> at android.view.View.draw(View.java:21586)
> at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
> at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
> at android.view.View.updateDisplayListIfDirty(View.java:20719)
> at android.view.View.draw(View.java:21586)
> at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
> at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
> at android.view.View.draw(View.java:21863)
> at com.android.internal.policy.DecorView.draw(DecorView.java:1083)
> at android.view.View.updateDisplayListIfDirty(View.java:20733)
> at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:725)
> at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:731)
> at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:840)
> at android.view.ViewRootImpl.draw(ViewRootImpl.java:3932)
> at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3706)
> at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3014)
> 2019-08-01 11:57:08.157 11355-11355/net.overc.android.mobile E/AndroidRuntime: at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1873)
> at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8478)
> at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
> at android.view.Choreographer.doCallbacks(Choreographer.java:761)
> at android.view.Choreographer.doFrame(Choreographer.java:696)
> at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
> at android.os.Handler.handleCallback(Handler.java:873)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at android.os.Looper.loop(Looper.java:214)
> at android.app.ActivityThread.main(ActivityThread.java:6990)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

How solve that ?

**Comment by burhanrashid52** [comment] 2020-11-01 03:03
This issue is fixed in 1.1.0 release. Reopen this if you are still facing this issue.

**Closed by burhanrashid52** 2020-11-01 03:03 UTC
Labels: need more info

**Comment by HritikBhat** [comment] 2020-11-02 10:48
This happens when an image is saved with a large sticker on it.

E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.digitalvtalks.data, PID: 24741
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at android.view.ViewGroup.getAndVerifyPreorderedView(ViewGroup.java:3756)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4243)
        at android.view.View.draw(View.java:20346)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4459)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4245)
        at android.view.View.buildDrawingCacheImpl(View.java:19720)
        at android.view.View.buildDrawingCache(View.java:19586)
        at android.view.View.getDrawingCache(View.java:19492)
        at android.view.View.getDrawingCache(View.java:19457)
        at ja.burhanrashid52.photoeditor.PhotoEditor$6$1.doInBackground(PhotoEditor.java:745)
        at ja.burhanrashid52.photoeditor.PhotoEditor$6$1.doInBackground(PhotoEditor.java:731)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764)
