### ISSUE TITLE
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'ossrhUsername' for Credentials [username: null] of type org.gradle.internal.credentials.DefaultPasswordCredentials_Decorated.

### ISSUE THREAD

**Issue by BerdiyorovAbrorjon** [burhanrashid52/PhotoEditor#335] opened 2021-04-08 09:05 UTC
getting clone from forked repo

**Comment by burhanrashid52** [comment] 2021-04-08 09:27
Duplicate of #332

**Closed by burhanrashid52** 2021-04-08 09:27 UTC
