### ISSUE TITLE
I have made some extensions based on your library, including changes to the way the image is saved, gif composition, repeated editing, and bug fixes, but I encountered some problems when generating images, when the view was rotated and zoomed. After that, I was unable to get the correct location information. Can you give me some help?

### ISSUE THREAD

**Issue by Swordce** [burhanrashid52/PhotoEditor#61] opened 2018-07-10 09:06 UTC

**Comment by burhanrashid52** [comment] 2018-07-16 13:23
Duplicate of #60

**Closed** 2018-07-17 11:47 UTC
Labels: duplicate, question
