### ISSUE TITLE
onEditTextChangeListener getting called even for slight adjustment of text on the image

### ISSUE THREAD

**Issue by shrikanth7698** [burhanrashid52/PhotoEditor#306] opened 2021-01-19 20:25 UTC
Steps to reproduce:
1. Add a text to photo editor
   `photoEditor.addText(
                                binding.editAddedText.text.toString(),
                                addEditTextColor
                        )`
2. Then move the added text by a small distance. 

This will call `onEditTextChangeListener` immediately which results in opening of the text edit window which interrupts the text movement gesture.

**Comment by burhanrashid52** [comment] 2021-01-20 11:37
I checked in the sample app. I am not able to reproduce it. Can you share your code snippet?

**Comment by codecracker1993** [comment] 2021-02-23 17:24
> Steps to reproduce:
> 
> 1. Add a text to photo editor
>    `photoEditor.addText( binding.editAddedText.text.toString(), addEditTextColor )`
> 2. Then move the added text by a small distance.
> 
> This will call `onEditTextChangeListener` immediately which results in opening of the text edit window which interrupts the text movement gesture.

Hi 
is your issue resolved? Leme know, I am also facing same issue.

Thanks

**Comment by burhanrashid52** [comment] 2021-06-02 03:02
Closing this issue due to no acitivty.

**Closed by burhanrashid52** 2021-06-02 03:02 UTC
