### ISSUE TITLE
 Caused by java.lang.IndexOutOfBoundsException Index: 1, Size: 0

### ISSUE THREAD

**Issue by hamza-ahmed** [burhanrashid52/PhotoEditor#455] opened 2022-05-10 08:02 UTC
java.util.ArrayList.get (ArrayList.java:437)
android.view.ViewGroup.getAndVerifyPreorderedView (ViewGroup.java:4564)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:5090)
android.view.View.draw (View.java:23771)
android.view.ViewGroup.drawChild (ViewGroup.java:5336)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:5093)
android.view.View.draw (View.java:23904)
ja.burhanrashid52.photoeditor.PhotoSaverTask.captureView (PhotoSaverTask.java:161)
ja.burhanrashid52.photoeditor.PhotoSaverTask.buildBitmap (PhotoSaverTask.java:104)
ja.burhanrashid52.photoeditor.PhotoSaverTask.saveImageAsBitmap (PhotoSaverTask.java:76)
ja.burhanrashid52.photoeditor.PhotoSaverTask.doInBackground (PhotoSaverTask.java:68)
ja.burhanrashid52.photoeditor.PhotoSaverTask.doInBackground (PhotoSaverTask.java:23)
android.os.AsyncTask$3.call (AsyncTask.java:394)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:305)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:923)

**Comment by burhanrashid52** [comment] 2022-05-10 11:03
Duplicate of #374

**Closed by burhanrashid52** 2022-05-10 11:03 UTC
Labels: duplicate
