### ISSUE TITLE
QUESTION: How will I load an image with Glide?

### ISSUE THREAD

**Issue by RoblokazPlays** [burhanrashid52/PhotoEditor#282] opened 2020-10-26 15:12 UTC
I'm making a messaging app in Android and like every other app, there is a photo editor when uploading photos. This library looked like an amazing choice.

In ChatActivity, it's passing the photo uri with `putExtra();` over to my EditorActivity. How will I load the uri of this image with Glide into the `PhotoEditorView`?

**Also some more things**

- Please consider making the wiki pages **more detailed.** It would help a lot for many people if you went into greater detail into what the library can do, and also go into detail on how to implement each one of these features. For dumb people like me, it would be nice.

Thanks a lot.

**Comment by burhanrashid52** [comment] 2020-11-01 03:00
Duplicate of #247 
The propject is open. If you feel the doc need improvement than feel free to add PR for wiki documentation.

**Closed by burhanrashid52** 2020-11-01 03:00 UTC
