### ISSUE TITLE
Add Frame

### ISSUE THREAD

**Issue by anila791** [burhanrashid52/PhotoEditor#264] opened 2020-07-29 14:39 UTC
kindlt tell how add frame

**Comment by AdhseOne** [comment] 2020-07-30 00:29
You can put a drawing with a stroke as a background in PhotoEditorView. If you mean something else, send an image to understand. :'v

**Comment by AdhseOne** [comment] 2020-07-30 00:30
You can put a drawing with a stroke as a background in PhotoEditorView. If you want to say something else, send an image to understand. :'v

**Comment by AdhseOne** [comment] 2020-07-30 00:31
> por favor diga cómo agregar marco

You can put a drawing with a stroke as a background in PhotoEditorView. If you want to say something else, send an image to understand. : 'v

**Comment by burhanrashid52** [comment] 2020-09-15 09:07
Duplicate of #8

**Closed by burhanrashid52** 2020-09-15 09:07 UTC
Labels: duplicate
