### ISSUE TITLE
Initial set image is appearing smaller than the original size

### ISSUE THREAD

**Issue by NavjotSinghSeraphic** [burhanrashid52/PhotoEditor#565] opened 2024-08-23 07:58 UTC
@burhanrashid52 
Actually originally the image is big in size but when we try to edit with photo editor its size appears smaller![image](https://github.com/user-attachments/assets/7deb9e2d-b88f-4482-8b7f-82a1ee91ed9d)

![image](https://github.com/user-attachments/assets/aac71ed4-4864-4154-b664-b1fc2b28811d)

**Comment by burhanrashid52** [comment] 2024-08-25 13:09
Duplicate of #10

**Closed by burhanrashid52** 2024-08-25 13:09 UTC
