### ISSUE TITLE
Memory out of bond

### ISSUE THREAD

**Issue by koradiyadhaval** [burhanrashid52/PhotoEditor#193] opened 2019-10-10 07:37 UTC
when i am changing filter pattern one by one at that time  high memory consuming this library after few second application crash because memory of bound exception showing in logs. Please try to capture any image using camera and that after apply all fiter one by one and check memeory usage in android studio. in my case current memory accoupied 0.9 GB [(Profilter).]
![Screenshot from 2019-10-10 13-07-56](https://user-images.githubusercontent.com/55177691/66548547-1350e580-eb5f-11e9-88b8-acd0bea04de9.png)

**Comment by burhanrashid52** [comment] 2019-10-10 10:57
Duplicate of #48

**Closed** 2020-10-19 03:06 UTC
Labels: duplicate

**Comment by koradiyadhaval** [comment] 2020-10-19 04:56
this issue is currently available is last version not resolved still date

**Comment by burhanrashid52** [comment] 2020-10-19 05:14
Yes, correct. This is just a duplicate issue of the existing one and that issue #48 is still open. It helps us to collect all information at single place.
