### ISSUE TITLE
MultiTouchListener has a bug with stickers

### ISSUE THREAD

**Issue by potibor** [burhanrashid52/PhotoEditor#93] opened 2018-10-18 14:03 UTC
when sticker is not in view bounds from left and right side , sticker can be disappear.
 You are not controlling that issue

**Comment by burhanrashid52** [comment] 2018-10-18 14:28
Can share the video?

**Comment by potibor** [comment] 2018-10-18 15:03
[device-2018-10-18-180115.webm.zip](https://github.com/burhanrashid52/PhotoEditor/files/2492429/device-2018-10-18-180115.webm.zip)

**Comment by burhanrashid52** [comment] 2018-10-19 03:44
Duplicate of #51

**Closed** 2019-03-14 15:55 UTC
Labels: duplicate
