### ISSUE TITLE
Feature Request - Gif Sticker Support

### ISSUE THREAD

**Issue by Vitor238** [burhanrashid52/PhotoEditor#228] opened 2020-02-05 15:36 UTC
Hi! Can you add gif sticker support (like instagram) to the library?
How can I add this feature to my app?
Thanks in advance!

**Comment by pramodkr123** [comment] 2020-07-21 08:10
Duplicate of #

**Comment by sambhav2358** [comment] 2022-11-30 14:44
@Vitor238, then it will become another gif or vidoe. After adding the gif, the file wont remain an image anymore. And since this is only an image editor, u cant add gifs!

**Closed** 2022-11-30 17:22 UTC
