### ISSUE TITLE
Problem placing a sticker on image

### ISSUE THREAD

**Issue by xelanac** [burhanrashid52/PhotoEditor#336] opened 2021-04-08 10:39 UTC
Problem starts when I have to place a sticker on canvas/image: the sticker returns back to the center, it's like there is gravity.
Other project's dependencies colud create conflicts with this library?

Canvas matches parent's width and height, as you can see in the xml below:

    <ja.burhanrashid52.photoeditor.PhotoEditorView
        android:id="@+id/photoEditorView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginBottom="?attr/actionBarSize">
    </ja.burhanrashid52.photoeditor.PhotoEditorView>

**Comment by burhanrashid52** [comment] 2021-04-08 11:49
Duplicate of #333

**Closed by burhanrashid52** 2021-04-08 11:49 UTC
