### ISSUE TITLE
After applying a filter; stickers, text, and emoji's will clip.

### ISSUE THREAD

**Issue by nickakaloki** [burhanrashid52/PhotoEditor#129] opened 2019-01-26 02:22 UTC
After applying a filter; Stickers, text, and emoji's will clip or disappear while moving them. Only happens with some backgrounds. Try it with [this picture.](https://techiecrunch.com/wp-content/uploads/2017/09/wallpaper07.jpg)

**Comment by burhanrashid52** [comment] 2019-01-26 03:16
Duplicate of #111

**Comment by nickakaloki** [comment] 2019-01-26 03:56
It's not just clipping at the bottom. I think this bug is something entirely different.

**Comment by burhanrashid52** [comment] 2019-01-26 04:09
Can you share the steps to reproduce it and screenshots

**Comment by nickakaloki** [comment] 2019-01-26 04:34
Using your example app. Load this [background](https://techiecrunch.com/wp-content/uploads/2017/09/wallpaper07.jpg). Apply any filter. Now choose an emoji, text or sticker. Move it around the screen. (You might need to shrink the sticker)
![clipping](https://user-images.githubusercontent.com/39487377/51782640-b6f58500-20f9-11e9-8182-dce829fe25ed.jpeg)

**Comment by burhanrashid52** [comment] 2019-01-26 05:12
Is thin happing with all the images and stickers?

**Comment by nickakaloki** [comment] 2019-01-26 05:18
Only with images where the width is less then height. 1080x1920. Even photos taken with the camera. All the text, emoji and stickers are clipping. 

Tested on samsung S5 and S7 edge so far.

**Comment by shafimuhammed** [comment] 2019-05-14 06:49
I have fixed this. Use `view.bringToFront();` in `onTouch` event on MultiTouchListener class. See below

`switch (action & event.getActionMasked()) {
            case MotionEvent.ACTION_DOWN:
                mPrevX = event.getX();
                mPrevY = event.getY();
                mPrevRawX = event.getRawX();
                mPrevRawY = event.getRawY();
                mActivePointerId = event.getPointerId(0);
                if (deleteView != null) {
                    deleteView.setVisibility(View.VISIBLE);
                }
                **view.bringToFront();**
                firePhotoEditorSDKListener(view, true);
                break;
            case MotionEvent.ACTION_MOVE:
                int pointerIndexMove = event.findPointerIndex(mActivePointerId);
                if (pointerIndexMove != -1) {
                    float currX = event.getX(pointerIndexMove);
                    float currY = event.getY(pointerIndexMove);
                    if (!mScaleGestureDetector.isInProgress()) {
                        adjustTranslation(view, currX - mPrevX, currY - mPrevY);
                    }
                }
                **view.bringToFront();**
                break;
            case MotionEvent.ACTION_CANCEL:
                mActivePointerId = INVALID_POINTER_ID;
                break;
            case MotionEvent.ACTION_UP:
                mActivePointerId = INVALID_POINTER_ID;
                if (deleteView != null && isViewInBounds(deleteView, x, y)) {
                    if (onMultiTouchListener != null)
                        onMultiTouchListener.onRemoveViewListener(view);
                } else if (!isViewInBounds(photoEditImageView, x, y)) {
                    view.animate().translationY(0).translationY(0);
                }
                if (deleteView != null) {
                    deleteView.setVisibility(View.GONE);
                }
                **view.bringToFront();**
                firePhotoEditorSDKListener(view, false);
                break;
            case MotionEvent.ACTION_POINTER_UP:
                int pointerIndexPointerUp = (action & MotionEvent.ACTION_POINTER_INDEX_MASK) >> MotionEvent.ACTION_POINTER_INDEX_SHIFT;
                int pointerId = event.getPointerId(pointerIndexPointerUp);
                if (pointerId == mActivePointerId) {
                    int newPointerIndex = pointerIndexPointerUp == 0 ? 1 : 0;
                    mPrevX = event.getX(newPointerIndex);
                    mPrevY = event.getY(newPointerIndex);
                    mActivePointerId = event.getPointerId(newPointerIndex);
                }
                **view.bringToFront();**
                break;
        }`

**Comment by ExquisiteKyle** [comment] 2019-06-14 00:28
> I have fixed this. add `view.bringToFront();` in `onTouch` event on MultiTouchListener class.
> Add this on following MotionEvents at the end
> 
> `MotionEvent.ACTION_MOVE`
> `MotionEvent.ACTION_DOWN`
> `MotionEvent.ACTION_UP`
> `MotionEvent.ACTION_POINTER_UP`

Simply adding view.bringtoFront() on the existing cases didn't work for me.
Adding a default case at the end of the switch statement with your answer solved mine.

```
 default:
     view.bringToFront();
```

**Comment by burhanrashid52** [comment] 2019-06-14 01:15
@shafimuhammed @ExquisiteKyle You can generate a PR if you have fixed this issue.

**Comment by gmp009** [comment] 2019-08-03 08:55
> Using your example app. Load this [background](https://techiecrunch.com/wp-content/uploads/2017/09/wallpaper07.jpg). Apply any filter. Now choose an emoji, text or sticker. Move it around the screen. (You might need to shrink the sticker)
> ![clipping](https://user-images.githubusercontent.com/39487377/51782640-b6f58500-20f9-11e9-8182-dce829fe25ed.jpeg)

I am trying to achieve this UI but IDK how to do that. in the readme file there is no way to achieve this kind of setup i am Nob here not much experience so can you please guide me how to get this complete UI with Text and Stickers on my email ? gmpanh@gmail.com

**Comment by vasanihardik** [comment] 2020-03-19 09:50
[https://github.com/burhanrashid52/PhotoEditor/issues/111#issuecomment-601044700](check this ans)

**Closed** 2021-05-13 13:31 UTC
Labels: duplicate
