### ISSUE TITLE
All layers removed after Screen rotate

### ISSUE THREAD

**Issue by dannyschapeit** [burhanrashid52/PhotoEditor#471] opened 2022-08-09 05:58 UTC
**Describe the bug**
When I rotate the device screen, all layers like Text, Brush,... are removed because the state is not saved and restored.

**To Reproduce**
1. Draw something
2. Rotate the device

**Expected behavior**
On instance save the current state should saved and restored in `onRestoreInstanceState()`

**Smartphone Info:**
 - Device: Samsung Tab Active 3
 - OS: Android 12

**Additional context**
Can anyone help me to save the state of PhotoEditor and PhotoEditorView and restoring it after rotate the device?

**Comment by burhanrashid52** [comment] 2022-08-09 10:50
Duplicate of #302

**Closed** 2022-08-09 11:11 UTC
Labels: duplicate
